title: Yuandong Yang's Homepage
page-top-title: Yuandong Yang
top-section-bg-text: Video Understanding
home-subtitle: Yuandong Yang;杨元东
copyright-text: '&copy; Yuandong Yang 2026. All Rights Reserved.'
